baseURL = "https://a.l3x.in/"
languageCode = "en-us"
title = "Al3x"

[params]
  author = "Alexander Fortin"
  description = "Alexander Fortin's personal web site"
  listed_articles = 3

[menu]

  [[menu.main]]
    name = "home"
    url = "/"
    weight = -1

  [[menu.main]]
    name = "about"
    url = "https://cv.l3x.in/about/"
    weight = 1

  [[menu.main]]
    name = "hire me!"
    url = "/hire-me/"
    weight = 3

  [[menu.main]]
    name = "RSS"
    class = "rss"
    url = "/feed.xml"
    weight = 4

  [[menu.socialnetworks]]
    name = "github"
    url = "https://github.com/shaftoe"
    weight = 1

  [[menu.socialnetworks]]
    name = "mixcloud"
    url = "https://www.mixcloud.com/al3xf"
    weight = 2

  [[menu.socialnetworks]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCb5FGNik4wXGrVGRS1x2JZw"
    weight = 2

  [[menu.socialnetworks]]
    name = "mastodon"
    url = "https://fosstodon.org/@alex/"
    weight = 3

  [[menu.socialnetworks]]
    name = "twitter"
    url = "https://www.twitter.com/alexanderfortin"
    weight = 3

  [[menu.socialnetworks]]
    name = "goodreads"
    url = "https://www.goodreads.com/user/show/20133803-alexander"
    weight = 4

  [[menu.socialnetworks]]
    name = "linkedin"
    url = "http://www.linkedin.com/in/alexanderfortin"
    weight = 4

  [[menu.socialnetworks]]
    name = "reddit"
    url = "https://www.reddit.com/user/AlexanderFortin"
    weight = 4

  [[menu.socialnetworks]]
    name = "instagram"
    url = "https://www.instagram.com/al3xfor/"
    weight = 5

  [[menu.socialnetworks]]
    name = "flickr"
    url = "https://www.flickr.com/photos/ali3n0/"
    weight = 5

  [[menu.socialnetworks]]
    name = "facebook"
    url = "https://www.facebook.com/alexander.fortin.9"
    weight = 10

[taxonomies]
  genre = "genres"
