baseURL = "https://a.l3x.in/"
languageCode = "en-us"
title = "Al3x"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = -100

  [[menu.socialnetworks]]
    name = "github"
    url = "https://github.com/shaftoe"
    weight = 1

  [[menu.socialnetworks]]
    name = "mixcloud"
    url = "https://www.mixcloud.com/al3xf"
    weight = 2

  [[menu.socialnetworks]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCb5FGNik4wXGrVGRS1x2JZw"
    weight = 3

  [[menu.socialnetworks]]
    name = "mastodon"
    url = "https://fosstodon.org/@alex/"
    weight = 4

  [[menu.socialnetworks]]
    name = "twitter"
    url = "https://twitter.com/alexanderfortin"
    weight = 5

  [[menu.socialnetworks]]
    name = "linkedin"
    url = "http://www.linkedin.com/in/alexanderfortin"
    weight = 6

  [[menu.socialnetworks]]
    name = "reddit"
    url = "https://reddit.com/FIXME"
    weight = 7

  [[menu.socialnetworks]]
    name = "instagram"
    url = "https://www.instagram.com/al3xfor/"
    weight = 8

  [[menu.socialnetworks]]
    name = "facebook"
    url = "https://www.facebook.com/alexander.fortin.9"
    weight = 9
