baseURL = "https://a.l3x.in/"
languageCode = "en-us"
title = "Al3x' personal home page"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
rssLimit = 20
enableRobotsTXT = true
disqusShortname = "a-l3x-in"

[params]
  author = "Al3x"
  author_full = "Alexander Fortin"
  currencies = [["USD", "🇺🇸"], ["EUR", "🇪🇺"], ["DOP", "🇩🇴"], ["RON", "🇷🇴"]]
  description = "Alexander Fortin's personal web site"
  listed_articles = 3
  feed = "/index.xml"
  staticCommentsAkismetKey = "81276ea55ef9"
  staticCommentsUrl = "https://comments.l3x.in/new"
  staticCommentsRepo = "shaftoe/personal-website"
  twitter_handle = "alexanderfortin"
  umami_website_id = "d2f0933f-644c-42ea-8b50-ad2766838043"

[menu]

  [[menu.main]]
    name = "home"
    url = "/"
    weight = -1

  [[menu.main]]
    name = "about"
    url = "https://cv.l3x.in/about/"
    weight = 1

  [[menu.main]]
    name = "hire me!"
    url = "https://www.toptal.com/resume/alexander-fortin"
    weight = 3

  [[menu.main]]
    name = "RSS"
    weight = 4

  [[menu.content]]
    name = "Tech Blog"
    url = "/blog"
    weight = 1

  [[menu.content]]
    name = "Micro Blog"
    url = "https://fosstodon.org/@alex/"
    weight = 2

  [[menu.content]]
    name = "Music Mixes"
    url = "https://www.mixcloud.com/al3xf"
    weight = 3

  [[menu.content]]
    name = "Videos"
    url = "https://www.youtube.com/channel/UCb5FGNik4wXGrVGRS1x2JZw"
    weight = 4

  [[menu.content]]
    name = "Contact"
    url = "/contact"
    weight = 5

  [[menu.content]]
    name = "Privacy"
    url = "/privacy"
    weight = 6

  [[menu.content]]
    name = "Statistics"
    url = "https://cloud.umami.is/share/9JLnEORYeXnNihO1/a.l3x.in"
    weight = 6

  [[menu.content]]
    name = "License"
    url = "https://creativecommons.org/licenses/by-sa/4.0/"
    weight = 7

  [[menu.socialnetworks]]
    name = "github"
    url = "https://github.com/shaftoe"
    weight = 1

  [[menu.socialnetworks]]
    name = "mixcloud"
    url = "https://www.mixcloud.com/al3xf"
    weight = 2

  [[menu.socialnetworks]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCb5FGNik4wXGrVGRS1x2JZw"
    weight = 2

  [[menu.socialnetworks]]
    name = "mastodon"
    url = "https://fosstodon.org/@alex/"
    weight = 3

  [[menu.socialnetworks]]
    name = "x-twitter"
    url = "https://x.com/alexanderfortin"
    weight = 3

  [[menu.socialnetworks]]
    name = "goodreads"
    url = "https://www.goodreads.com/user/show/20133803-alexander"
    weight = 4

  [[menu.socialnetworks]]
    name = "linkedin"
    url = "http://www.linkedin.com/in/alexanderfortin"
    weight = 4

  [[menu.socialnetworks]]
    name = "reddit"
    url = "https://www.reddit.com/user/AlexanderFortin"
    weight = 4

  [[menu.socialnetworks]]
    name = "instagram"
    url = "https://www.instagram.com/al3xfor/"
    weight = 5

  [[menu.socialnetworks]]
    name = "flickr"
    url = "https://www.flickr.com/photos/ali3n0/"
    weight = 5

  [[menu.socialnetworks]]
    name = "facebook"
    url = "https://www.facebook.com/alexander.fortin.9"
    weight = 10

  [[menu.jamstack]]
    name = "Website Source Code"
    url = "https://github.com/shaftoe/personal-website"
    weight = 1

  [[menu.jamstack]]
    name = "Made with Hugo"
    url = "https://gohugo.io/"
    weight = 2

  [[menu.jamstack]]
    name = "Comments by static-comments"
    url = "https://github.com/shaftoe/static-comments"
    weight = 3

  [[menu.jamstack]]
    name = "Fonts by Google"
    url = "https://fonts.google.com/"
    weight = 4

  [[menu.jamstack]]
    name = "Icons by Font Awesome"
    url = "https://fontawesome.com/"
    weight = 4

  [[menu.jamstack]]
    name = "Build automation in Node.js"
    url = "https://github.com/shaftoe/personal-website/tree/master/lib"
    weight = 5

  [[menu.jamstack]]
    name = "Built, hosted and distributed by Netlify"
    url = "https://www.netlify.com/"
    weight = 6

  [[menu.jamstack]]
    name = "Analytics by Umami"
    url = "https://cloud.umami.is/share/9JLnEORYeXnNihO1/a.l3x.in"
    weight = 6

[taxonomies]
  tag = "tags"

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^babel$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
