[build]
  command = "make deploy"
  publish = "public/"

[build.environment]
  BUILD_ENV = "production"
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_MODULES_PATH = "/opt/build/repo/node_modules"

[context.dev.environment]
  BUILD_ENV = "development"
  HUGO_ENV = "development"

[[headers]]
  for = "/expense"
  [headers.values]
    Basic-Auth = "alex:changeme"
