[build]
  command = "make deploy"
  publish = "public/"

[build.environment]
  BUILD_ENV = "production"
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_MODULES_PATH = "/opt/build/repo/node_modules"
