name: "Deploy"

description: "Trigger a Netlify build"

inputs:
  netlify-build-hook:
    description: "Netlify build hook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Netlify Build
      shell: bash
      run: |
        curl -X POST -w "\nNetlify build triggered: %{http_code}\n" \
          "${{ inputs.netlify-build-hook }}"
