name: Deploy

on:
  workflow_call:
    secrets:
      netlify-build-hook:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Trigger Netlify Build
        shell: bash
        run: |
          curl -X POST -w "\nNetlify build triggered: %{http_code}\n" \
            "${{ secrets.netlify-build-hook }}"
