name: Deploy

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: |
          curl -X POST -w "\nNetlify build triggered: %{http_code}\n" \
            ${{ secrets.NETLIFY_BUILD_HOOK }}
