name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: Release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    uses: ./.github/workflows/deploy.yml
    secrets:
      netlify-build-hook: ${{ secrets.NETLIFY_BUILD_HOOK }}
