name: Run test suite

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - uses: pnpm/action-setup@v6

      - run: pnpm install --frozen-lockfile

      - run: pnpm run validate

      - run: pnpm run build

      - run: pnpm run test
